name: Docker Image Sync

on:
  workflow_dispatch:
    inputs:
      image-name:
        description: 'Docker Image'
        required: true

jobs:

  build-and-upload:
    runs-on: ubuntu-latest
    environment: AliDocker

    env:
      ORIGIN_REGISTRY: docker.io
      REGISTRY: ${{ vars.REGISTRY }}
      REGISTRY_REPO: ${{ vars.REGISTRY_REPO }}

    steps:
    - name: Update Image Name
      env:
        DOCKER_IMAGE: ${{ github.event.inputs.image-name }}
      run: |
        if [ "${DOCKER_IMAGE//\//}" == "${DOCKER_IMAGE}" ]; then
          echo "DOCKER_IMAGE=library/${DOCKER_IMAGE}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${DOCKER_IMAGE}" >> $GITHUB_ENV
        else
          echo "DOCKER_IMAGE=${DOCKER_IMAGE}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${DOCKER_IMAGE##*/}" >> $GITHUB_ENV
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://${{ env.ORIGIN_REGISTRY }}/${{ env.DOCKER_IMAGE }} docker://${{ env.REGISTRY }}/${{ env.REGISTRY_REPO }}/${{ env.IMAGE_NAME }}
